apiVersion: batch/v1
kind: CronJob
metadata:
  name: git2consul-job
  namespace: ft-transverse-git2consul

spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - image: cimpress/git2consul
            name: git2consul
            command: ["/bin/sh","-c","git2consul --config-file $(CONFIGURATION_FILE)"]
            resources: {}
            env:
            - name: CONSUL_ENDPOINT
              value: "consul-consul-server.ft-transverse-consul.svc.cluster.local"
            - name: CONSUL_PORT
              value: "8500"
            - name: CONFIGURATION_FILE
              value: "/tmp/configuration.json"
            volumeMounts:
            - name: configuration
              mountPath: /tmp/configuration.json
              subPath: configuration.json
          volumes:
          - name: configuration
            configMap:
              name: configuration-file